### ISSUE TITLE
[Bug] Typography not accessible for reading disability

### ISSUE THREAD

**Issue by YuriDevAT** [YuriDevAT/accessibility-first#30]
### Description

The current font face has similar or identical characters for at least the letters uppercase I, lowercase L and most likly number 1.

**Comment by pragyamishra56** [comment]
## Ma'am, do you mean that the typography should be changed to be accessible for reading?

![Screenshot 2023-12-09 205149](https://github.com/YuriDevAT/accessibility-first/assets/115208912/17ed2217-5d37-4d40-8f63-ce6f05e9022f)

**Comment by YuriDevAT** [comment]
Yes, exactly. You can view examples on [WebAIM's article about Typefaces and Fonts](Typefaces and Fonts).

**Comment by pragyamishra56** [comment]
Mam if it would possible or allow me that i can work on this issue

**Comment by YuriDevAT** [comment]
Thanks for you interest, but this project is not an open source or community project.
