### ISSUE TITLE
[FEATURE] Dark and Light Mode Icons Placement

### ISSUE THREAD

**Issue by pragyamishra56** [YuriDevAT/accessibility-first#32]
### Description

I suggest relocating the dark and light mode icons to the top right of the web page, adjacent to the "Accessibility First" section. This placement ensures easy accessibility and enhances user experience.

Currently, the icons are located bottom of the page . By moving them to the suggested position, users can quickly toggle between dark and light modes without scrolling or searching for the controls.

I have tested this layout adjustment and found that it improves the accessibility and visibility of the dark and light mode options. Users can now seamlessly switch between modes, aligning with the "Accessibility First" principle.

Please consider implementing this change for a more user-friendly interface. Thank you!

### Screenshots

![Screenshot 2023-12-09 203410](https://github.com/YuriDevAT/accessibility-first/assets/115208912/1476ad22-18a8-4433-9439-0c6af8fae2bc)

**Comment by YuriDevAT** [comment]
Thanks for the suggestion. This is already handled with issue #31 . Currently there is no header planned, maybe in a future version.

**Comment by pragyamishra56** [comment]
I appreciate your response Mam
